spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create  # (1) ??? ?? ??
    show-sql: true      # (2) SQL ?? ??
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        default_batch_fetch_size: 100
    open-in-view: false
  logging.level:
    org.hibernate.SQL: debug


  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

server:
  servlet:
    encoding:
      force-response: true

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40
  data.rest:
    base-path: /api
    detection-strategy: annotated
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE